language: go

go: 1.7

dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install pkg-config libopus-dev moreutils

script:
  - gofmt -l . | tee /dev/stderr | ifne false
  - go test -v ./...
